### ISSUE TITLE
[request] example spell for example mod maybe?

### ISSUE THREAD

**Issue by NotTheRealRoKur0** [Dev0Louis/Nebula#17]
add an example in the readme.md for how to integrate a spell into your mod
which should contain
- how to add a spell
- how to execute this spell (with which method to use or such)
- and how to check mana from player/user (clientside)

would be pretty helpful, im new to java coding so i dont quite know how to integrate something like this.

**Comment by Dev0Louis** [comment]
Added a bit about the Spell creation.
I currently don't have that much time. 
I will add more in the future.
