### ISSUE TITLE
Minecraft 1.20.1 crash during launching

### ISSUE THREAD

**Issue by Kielbashnikov** [Dev0Louis/Nebula#36]
[16:59:14] [main/WARN]: Error loading class: dev/louis/nebula/Nebula$NebulaRegistries (java.lang.ClassNotFoundException: dev/louis/nebula/Nebula$NebulaRegistries)

[16:59:22] [main/WARN]: Error loading class: dev/louis/nebula/spell/SpellType (java.lang.ClassNotFoundException: dev/louis/nebula/spell/SpellType)

These errors are poping in log during mc startup with crash directy after second one.
Full log below. I have other mods but I've also created clear instance just with Nebula and Zauber, same outcome.
[latest.log](https://github.com/user-attachments/files/16601554/latest.log)

**Comment by Dev0Louis** [comment]
Can you please share the log that only has zauber and nebula containing this issue?

**Comment by Kielbashnikov** [comment]
There you go: 
[latest.log](https://github.com/user-attachments/files/16615196/latest.log)

**Comment by Dev0Louis** [comment]
For that version of Zauber you will need https://modrinth.com/mod/nebula/version/3.2.3 
I do not support these old versions so downgrading nebula is your only option

**Comment by Kielbashnikov** [comment]
Ok, so 3.2.3 is for 1.20.2 but I downgraded nebula to 3.2.0 and I also got a crash during startup. Log below.
[latest.log](https://github.com/user-attachments/files/16619833/latest.log)

**Comment by Dev0Louis** [comment]
> Ok, so 3.2.3 is for 1.20.2 but I downgraded nebula to 3.2.0 and I also got a crash during startup. Log below. [latest.log](https://github.com/user-attachments/files/16619833/latest.log)

Can you send the crash report too?
